In [1]:
#importing required libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
#reading dataset
df = pd.read_csv("FastFoodNutritionMenuV2.csv")

In [3]:
df.head()

Company                           Item Calories Calories from\nFat  \
0  McDonald’s                      Hamburger      250                 80   
1  McDonald’s                   Cheeseburger      300                110   
2  McDonald’s            Double Cheeseburger      440                210   
3  McDonald’s                       McDouble      390                170   
4  McDonald’s   Quarter Pounder® with Cheese      510                230   

  Total Fat\n(g) Saturated Fat\n(g) Trans Fat\n(g) Cholesterol\n(mg)  \
0              9                3.5            0.5                25   
1             12                  6            0.5                40   
2             23                 11            1.5                80   
3             19                  8              1                65   
4             26                 12            1.5                90   

  Sodium \n(mg) Carbs\n(g) Fiber\n(g) Sugars\n(g) Protein\n(g)  \
0           520         31          2           6           12   
1           750         33          2           6           15   
2          1150         34          2           7           25   
3           920         33          2           7           22   
4          1190         40          3           9           29   

  Weight Watchers\nPnts  
0                 247.5  
1                   297  
2                   433  
3                   383  
4                   502

In [4]:
#data preprocessing
#checking null values
df.isnull().sum()

Company                    0
Item                       0
Calories                   1
Calories from\nFat       506
Total Fat\n(g)            57
Saturated Fat\n(g)        57
Trans Fat\n(g)            57
Cholesterol\n(mg)          1
Sodium \n(mg)              1
Carbs\n(g)                57
Fiber\n(g)                57
Sugars\n(g)                1
Protein\n(g)              57
Weight Watchers\nPnts    261
dtype: int64

In [8]:
#remove null rows
df = df.dropna()


In [9]:
df.isnull().sum()

Company                  0
Item                     0
Calories                 0
Calories from\nFat       0
Total Fat\n(g)           0
Saturated Fat\n(g)       0
Trans Fat\n(g)           0
Cholesterol\n(mg)        0
Sodium \n(mg)            0
Carbs\n(g)               0
Fiber\n(g)               0
Sugars\n(g)              0
Protein\n(g)             0
Weight Watchers\nPnts    0
dtype: int64

In [11]:
#after removing null values
df.shape

(515, 14)

In [23]:
numeric=["Calories",    "Calories from\nFat"    ,"Total Fat\n(g)",  "Saturated Fat\n(g)",   "Trans Fat\n(g)",   "Cholesterol\n(mg)",    "Sodium \n(mg)",    "Carbs\n(g)",   "Fiber\n(g)",   "Sugars\n(g)"   ,"Protein\n(g)",    "Weight Watchers\nPnts"]

In [24]:
for col in numeric: df[col]= pd.to_numeric(df[col], errors='coerce')

In [25]:
df[numeric]= df[numeric].fillna(df[numeric].median())

In [26]:
df[numeric].head()

Calories  Calories from\nFat  Total Fat\n(g)  Saturated Fat\n(g)  \
0     250.0                80.0             9.0                 3.5   
1     300.0               110.0            12.0                 6.0   
2     440.0               210.0            23.0                11.0   
3     390.0               170.0            19.0                 8.0   
4     510.0               230.0            26.0                12.0   

   Trans Fat\n(g)  Cholesterol\n(mg)  Sodium \n(mg)  Carbs\n(g)  Fiber\n(g)  \
0             0.5               25.0          520.0        31.0         2.0   
1             0.5               40.0          750.0        33.0         2.0   
2             1.5               80.0         1150.0        34.0         2.0   
3             1.0               65.0          920.0        33.0         2.0   
4             1.5               90.0         1190.0        40.0         3.0   

   Sugars\n(g)  Protein\n(g)  Weight Watchers\nPnts  
0          6.0          12.0                  247.5  
1          6.0          15.0                  297.0  
2          7.0          25.0                  433.0  
3          7.0          22.0                  383.0  
4          9.0          29.0                  502.0

In [46]:
df= df.drop(columns=["Item"])
df= df.drop(columns=["Company"])

In [48]:
X=df[["Calories from\nFat",	"Total Fat\n(g)",	"Saturated Fat\n(g)",	"Trans Fat\n(g)",	"Cholesterol\n(mg)",	"Sodium \n(mg)",	"Carbs\n(g)",	"Fiber\n(g)",	"Sugars\n(g)",	"Protein\n(g)",	"Weight Watchers\nPnts"]]

In [49]:
y=df["Calories"]

In [50]:

model= LinearRegression()

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [52]:

model.fit(X_train, y_train)

LinearRegression()

In [53]:
y_predict =model.predict(X_test)

In [54]:
y_predict

array([ 9.03949658e+01, -2.98915039e-02,  2.67377358e+02, -8.92753395e-03,
       -2.98915039e-02,  5.59186940e+02,  1.89635859e+02,  3.99444352e+02,
        6.59786183e+02,  6.07942874e+01,  4.55556551e+02,  3.89607857e+02,
        3.79446355e+02,  4.19739058e+02,  7.50439099e+02,  2.10267477e+02,
        4.79883187e+02,  3.99754492e+02,  1.40043154e+02,  1.79810677e+02,
        7.06395380e+01,  1.49923685e+02,  1.50758551e+02,  2.59297637e+02,
        1.15858216e+03,  2.39797805e+02,  5.70129193e+02,  2.60202599e+02,
        3.49515679e+02,  2.60454576e+02,  1.89567727e+02,  1.22079808e+03,
        7.38012598e+02,  7.90318075e+02,  1.59352268e+02,  3.39475071e+02,
        1.20490208e+02,  9.05967248e+01,  4.20099240e+02,  1.13055130e-01,
        3.69505132e+02,  1.70063295e+02,  1.72774285e-02,  2.61421352e+02,
        5.78994734e+02,  1.80036412e+02,  4.29255315e+02,  2.80447017e+02,
        5.59681379e+02,  5.31370857e+02,  6.10376079e+02,  1.89492913e+02,
        7.73441311e-01,  

In [55]:
model.score(X_test, y_test)

0.9999089439030294

In [59]:
model.predict([[170, 18, 3.5, 0, 40, 640, 38, 2, 5, 15, 373.5]])           #12th row

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([379.22084988])

In [70]:
df.iloc[12].Calories

np.float64(380.0)

In [68]:
  model.predict([[5,0.5,0,0,5,35,49,2,44,2,252]])   #324th row

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([210.03509346])

In [67]:
df.iloc[324].Calories

np.float64(210.0)

In [71]:
mse= mean_squared_error(y_test, y_predict)
mse

5.515018202470747

In [72]:
import math  #rmse
math.sqrt(mse)

2.348407588658908